"""
Production API for NinaivX. Most endpoints require a valid Supabase token.

Flow:
  1. POST /api/auth/signup  -> creates the account AND profile, returns a token.
     (or POST /api/auth/login to get a token for an existing account)
  2. App sends `Authorization: Bearer <token>` on every request.
  3. Create personas, then chat by text or voice.
"""
import base64
import re
import httpx
from fastapi import APIRouter, Depends, HTTPException, UploadFile, File, Form, BackgroundTasks, Response
from sqlalchemy.orm import Session
from pydantic import BaseModel, field_validator, model_validator

from app.core.config import settings
from app.db.database import get_db
from app.db.models import User, Persona, PersonaType
from app.core.auth import get_current_user
from app.agents.graph import run_agent
from app.services.voice_service import voice_service

router = APIRouter(prefix="/api", tags=["NinaivX API"])

DEFAULT_VOICE_ID = "pNInz6obpgDQGcFmaJgB"  # ElevenLabs "Adam" fallback
FLASH_TTS_MODEL = "eleven_flash_v2_5"       # lowest-latency model for live voice calls

# Minimum age to create an account. Set to 18 so the study involves only adults who
# can give their own informed consent — this keeps research ethics approval simple
# (no parental/guardian consent or safeguarding of minors required).
MIN_SIGNUP_AGE = 18

# ---- Strict input-validation limits (enforced server-side on every request) ----
MAX_HUMAN_AGE = 120          # sanity ceiling for any age
MIN_PASSWORD_LEN = 8         # minimum account password length
MIN_PERSONALITY_LEN = 10     # a persona needs a meaningful personality description
PERSONA_AGE_MIN = 1          # a persona's age must be a real positive number
# Simple, dependency-free email check (Supabase does the authoritative validation).
_EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")

# Map a persona's language name to an ISO code, used to lock TTS pronunciation
# (so e.g. Tamil doesn't drift toward Hindi). Unknown languages fall back to auto-detect.
LANGUAGE_CODES = {
    "english": "en", "tamil": "ta", "hindi": "hi", "telugu": "te", "malayalam": "ml",
    "kannada": "kn", "spanish": "es", "french": "fr", "german": "de", "arabic": "ar",
    "mandarin": "zh", "chinese": "zh", "japanese": "ja", "korean": "ko", "portuguese": "pt",
}

def _lang_code(name: str | None) -> str | None:
    return LANGUAGE_CODES.get((name or "").strip().lower())

# AI-transparency disclosure shown by the app at onboarding and as an in-app indicator.
DISCLOSURE_NOTICE = (
    "This is an AI recreation based on the information provided. It is not the real person and "
    "cannot replace them; all replies are generated by artificial intelligence."
)


# ---------- Schemas ----------
class AuthRequest(BaseModel):
    email: str          # validated by Supabase Auth
    password: str

class SignupRequest(BaseModel):
    # One-step account creation: credentials + profile together.
    email: str
    password: str
    name: str
    age: int
    language: str = "English"

    @field_validator("email")
    @classmethod
    def _email_ok(cls, v: str) -> str:
        v = (v or "").strip()
        if not _EMAIL_RE.match(v):
            raise ValueError("Please enter a valid email address.")
        return v

    @field_validator("password")
    @classmethod
    def _password_ok(cls, v: str) -> str:
        if not v or len(v) < MIN_PASSWORD_LEN:
            raise ValueError(f"Password must be at least {MIN_PASSWORD_LEN} characters.")
        return v

    @field_validator("name", "language")
    @classmethod
    def _not_blank(cls, v: str) -> str:
        v = (v or "").strip()
        if not v:
            raise ValueError("This field is required.")
        return v

    @field_validator("age")
    @classmethod
    def _age_ok(cls, v: int) -> int:
        if v is None or v < MIN_SIGNUP_AGE or v > MAX_HUMAN_AGE:
            raise ValueError(f"You must be between {MIN_SIGNUP_AGE} and {MAX_HUMAN_AGE} to create an account.")
        return v

class PersonaCreate(BaseModel):
    persona_type: PersonaType
    name: str
    age: int
    gender: str
    relationship_with_user: str
    personality_text: str
    elevenlabs_voice_id: str          # required: a voice must be chosen before creating a persona
    cause_of_death: str | None = None
    year_of_passing: int | None = None  # legacy only: temporally grounds the persona's knowledge
    language: str | None = None       # e.g. "English", "Tamil"; falls back to the user's
    user_nickname: str | None = None  # what the persona calls the user (e.g. "beta")

    @field_validator("name", "gender", "relationship_with_user", "elevenlabs_voice_id")
    @classmethod
    def _required_text(cls, v: str) -> str:
        v = (v or "").strip()
        if not v:
            raise ValueError("This field is required.")
        return v

    @field_validator("personality_text")
    @classmethod
    def _personality_ok(cls, v: str) -> str:
        v = (v or "").strip()
        if len(v) < MIN_PERSONALITY_LEN:
            raise ValueError(f"Please describe the personality in at least {MIN_PERSONALITY_LEN} characters.")
        return v

    @field_validator("age")
    @classmethod
    def _persona_age_ok(cls, v: int) -> int:
        if v is None or v < PERSONA_AGE_MIN or v > MAX_HUMAN_AGE:
            raise ValueError(f"Age must be a number between {PERSONA_AGE_MIN} and {MAX_HUMAN_AGE}.")
        return v

    @field_validator("cause_of_death", "language", "user_nickname")
    @classmethod
    def _blank_to_none(cls, v: str | None) -> str | None:
        v = (v or "").strip()
        return v or None

    @field_validator("year_of_passing")
    @classmethod
    def _year_ok(cls, v: int | None) -> int | None:
        if v is not None and (v < 1900 or v > 2100):
            raise ValueError("Year of passing must be a valid year (1900-2100).")
        return v

    @model_validator(mode="after")
    def _type_specific_rules(self):
        if self.persona_type == PersonaType.COMPANION:
            # A companion is a living adult friend — must be 18+.
            if self.age < MIN_SIGNUP_AGE:
                raise ValueError(f"A companion persona must be an adult ({MIN_SIGNUP_AGE} or over).")
            # Cause of death / year of passing only apply to a legacy (deceased) persona.
            if self.cause_of_death:
                raise ValueError("Cause of death only applies to a legacy (deceased) persona.")
            if self.year_of_passing:
                raise ValueError("Year of passing only applies to a legacy (deceased) persona.")
        # Legacy (deceased) personas may be any age (a lost child, etc.), so no lower age bound.
        return self

class PersonaUpdate(BaseModel):
    # All optional: only the fields you send get changed (partial update).
    name: str | None = None
    age: int | None = None
    gender: str | None = None
    relationship_with_user: str | None = None
    personality_text: str | None = None
    cause_of_death: str | None = None
    year_of_passing: int | None = None
    elevenlabs_voice_id: str | None = None
    language: str | None = None
    user_nickname: str | None = None

    @field_validator("year_of_passing")
    @classmethod
    def _year_ok(cls, v):
        if v is not None and (v < 1900 or v > 2100):
            raise ValueError("Year of passing must be a valid year (1900-2100).")
        return v

    @field_validator("name", "gender", "relationship_with_user", "elevenlabs_voice_id")
    @classmethod
    def _no_blank_when_sent(cls, v):
        # If the field is sent, it must not be blanked out.
        if v is not None and not str(v).strip():
            raise ValueError("This field cannot be empty.")
        return v.strip() if isinstance(v, str) else v

    @field_validator("personality_text")
    @classmethod
    def _personality_ok(cls, v):
        if v is not None and len(str(v).strip()) < MIN_PERSONALITY_LEN:
            raise ValueError(f"Please describe the personality in at least {MIN_PERSONALITY_LEN} characters.")
        return v.strip() if isinstance(v, str) else v

    @field_validator("age")
    @classmethod
    def _age_ok(cls, v):
        if v is not None and (v < PERSONA_AGE_MIN or v > MAX_HUMAN_AGE):
            raise ValueError(f"Age must be a number between {PERSONA_AGE_MIN} and {MAX_HUMAN_AGE}.")
        return v

class SelectVoiceRequest(BaseModel):
    voice_id: str

class ChatRequest(BaseModel):
    persona_id: str
    user_message: str


# ---------- Helper ----------
def _get_owned_persona(persona_id: str, user: User, db: Session) -> Persona:
    """Fetch a persona AND verify it belongs to the current user (prevents IDOR)."""
    persona = (
        db.query(Persona)
        .filter(Persona.id == persona_id, Persona.user_id == user.id)
        .first()
    )
    if not persona:
        raise HTTPException(status_code=404, detail="Persona not found or not yours.")
    return persona


# ---------- Auth (public) ----------
# These are thin proxies to Supabase Auth. Passwords are NEVER stored or hashed by
# this backend - Supabase remains the identity provider and owns credentials.
# They exist so the API can be used end-to-end (e.g. from Swagger) without the
# mobile app, and mirror exactly what the React Native client does via the SDK.

def _supabase_auth(path: str, payload: dict) -> dict:
    url = f"{settings.SUPABASE_URL}/auth/v1/{path}"
    headers = {"apikey": settings.SUPABASE_KEY, "Content-Type": "application/json"}
    try:
        r = httpx.post(url, headers=headers, json=payload, timeout=30.0)
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Could not reach Supabase Auth: {e}")

    data = r.json() if r.content else {}
    if r.status_code >= 400:
        msg = data.get("msg") or data.get("error_description") or data.get("error") or "Authentication failed."
        raise HTTPException(status_code=r.status_code, detail=msg)
    return data


@router.post("/auth/signup", tags=["Auth"])
def signup(body: SignupRequest, db: Session = Depends(get_db)):
    """
    Create an account AND the user's profile in one step.

    Takes email + password (credentials, stored by Supabase) together with the
    profile details (name, age, language, stored here). Returns an access token
    ready to paste into Swagger's "Authorize" button.

    If the Supabase project has "Confirm email" enabled, no token is returned until
    the email is confirmed; the profile is still created so it is ready on first login.

    Age restriction: only adults (>= MIN_SIGNUP_AGE) may register, so the project
    involves no minors — keeping research ethics approval straightforward. This
    (and all other input validation) is enforced by SignupRequest's validators,
    which reject invalid input with a 422 before this function runs.
    """
    data = _supabase_auth("signup", {"email": body.email, "password": body.password})
    uid = (data.get("user") or {}).get("id")
    access_token = data.get("access_token")

    if not uid:
        raise HTTPException(status_code=502, detail="Supabase did not return a user id.")

    # Create the profile row (id == Supabase Auth UUID). Idempotent if it already exists.
    if not db.query(User).filter(User.id == uid).first():
        db.add(User(id=uid, name=body.name, age=body.age, language=body.language))
        db.commit()

    return {
        "message": "Account and profile created." if access_token else
                   "Account and profile created, but email confirmation is required before logging in.",
        "email_confirmation_required": access_token is None,
        "access_token": access_token,
        "user_id": uid,
        "next_step": "Click Authorize with this token, then create a persona (POST /api/personas)."
                     if access_token else "Confirm the email, then POST /api/auth/login.",
    }


@router.post("/auth/login", tags=["Auth"])
def login(body: AuthRequest):
    """
    Log in with email + password and receive a Supabase access token.
    Paste the returned access_token into the Swagger "Authorize" button.
    """
    data = _supabase_auth("token?grant_type=password", {"email": body.email, "password": body.password})
    return {
        "access_token": data.get("access_token"),
        "refresh_token": data.get("refresh_token"),
        "token_type": data.get("token_type", "bearer"),
        "expires_in": data.get("expires_in"),
        "user_id": (data.get("user") or {}).get("id"),
        "next_step": "Click Authorize in Swagger and paste the access_token.",
    }


# ---------- Disclosure (public) ----------
@router.get("/disclosure")
def disclosure():
    """
    Public AI-transparency notice. The app shows this at onboarding and as a
    persistent in-app indicator, so users always know they are talking to an AI.
    """
    return {"disclosure": DISCLOSURE_NOTICE}


# ---------- Account ----------
@router.get("/me")
def me(user: User = Depends(get_current_user)):
    return {
        "id": user.id, "name": user.name,
        "age": user.age, "language": user.language,
        "disclosure": DISCLOSURE_NOTICE,
    }


# ---------- Personas ----------
@router.post("/personas")
def create_persona(body: PersonaCreate, user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    persona = Persona(
        user_id=user.id,
        persona_type=body.persona_type,
        name=body.name,
        age=body.age,
        gender=body.gender,
        relationship_with_user=body.relationship_with_user,
        personality_text=body.personality_text,
        cause_of_death=body.cause_of_death,
        year_of_passing=body.year_of_passing,
        elevenlabs_voice_id=body.elevenlabs_voice_id,
        language=body.language,
        user_nickname=body.user_nickname,
    )
    db.add(persona)
    db.commit()
    db.refresh(persona)
    return {"message": "Persona created.", "persona_id": persona.id}


@router.get("/personas")
def list_personas(user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    personas = db.query(Persona).filter(Persona.user_id == user.id).all()
    return [
        {
            "id": p.id, "name": p.name, "persona_type": p.persona_type.value,
            "relationship_with_user": p.relationship_with_user,
            "elevenlabs_voice_id": p.elevenlabs_voice_id,
        }
        for p in personas
    ]


def _persona_dict(p: Persona) -> dict:
    return {
        "id": p.id,
        "persona_type": p.persona_type.value,
        "name": p.name,
        "age": p.age,
        "gender": p.gender,
        "relationship_with_user": p.relationship_with_user,
        "personality_text": p.personality_text,
        "cause_of_death": p.cause_of_death,
        "year_of_passing": p.year_of_passing,
        "elevenlabs_voice_id": p.elevenlabs_voice_id,
        "language": p.language,
        "user_nickname": p.user_nickname,
        "disclosure": DISCLOSURE_NOTICE,
    }


@router.get("/personas/{persona_id}")
def get_persona(persona_id: str, user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    """Fetch one persona (must belong to the current user)."""
    return _persona_dict(_get_owned_persona(persona_id, user, db))


@router.patch("/personas/{persona_id}")
def update_persona(
    persona_id: str,
    body: PersonaUpdate,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Partial update: only the fields you send are changed (e.g. just the
    elevenlabs_voice_id, or just the personality_text). persona_type is fixed.
    """
    persona = _get_owned_persona(persona_id, user, db)
    changes = body.model_dump(exclude_unset=True)  # only fields the client actually sent
    # A companion persona must stay an adult (18+); legacy personas may be any age.
    if "age" in changes and persona.persona_type == PersonaType.COMPANION and changes["age"] < MIN_SIGNUP_AGE:
        raise HTTPException(
            status_code=400,
            detail=f"A companion persona must be an adult ({MIN_SIGNUP_AGE} or over).",
        )
    for field, value in changes.items():
        setattr(persona, field, value)
    db.commit()
    db.refresh(persona)
    return {"message": "Persona updated.", "persona": _persona_dict(persona)}


@router.delete("/personas/{persona_id}")
def delete_persona(persona_id: str, user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    """Delete a persona and its conversation memory (cascade)."""
    persona = _get_owned_persona(persona_id, user, db)
    db.delete(persona)
    db.commit()
    return {"message": "Persona deleted.", "persona_id": persona_id}


@router.post("/personas/{persona_id}/select-voice")
def select_voice(
    persona_id: str,
    body: SelectVoiceRequest,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Assign a ready-made voice (chosen from GET /api/voices) to a persona in one
    step. After this, all voice replies for the persona use this voice.
    """
    persona = _get_owned_persona(persona_id, user, db)
    persona.elevenlabs_voice_id = body.voice_id
    db.commit()
    return {"message": "Voice assigned.", "persona_id": persona.id, "elevenlabs_voice_id": body.voice_id}


# ---------- Chat (text) ----------
@router.post("/chat")
def chat(
    body: ChatRequest,
    background_tasks: BackgroundTasks,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Text chat. Memory summary is updated in the background for low latency."""
    persona = _get_owned_persona(body.persona_id, user, db)
    try:
        reply = run_agent(
            db=db, persona_id=persona.id, user_message=body.user_message,
            background_tasks=background_tasks,
        )
        return {"reply": reply}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Agent error: {e}")


# ---------- Warm-up (call before a voice session to avoid a cold first turn) ----------
@router.post("/warmup")
def warmup(user: User = Depends(get_current_user)):
    """Pre-warm the fast voice model so the first call turn isn't a cold start."""
    from app.services.llm_service import get_llm
    from langchain_core.messages import HumanMessage
    try:
        get_llm(model_id=settings.BEDROCK_VOICE_MODEL_ID, max_tokens=5).invoke([HumanMessage(content="hi")])
        return {"warm": True}
    except Exception:
        return {"warm": False}


# ---------- Speech-to-text only (for review-before-send in Voice mode) ----------
@router.post("/stt")
async def speech_to_text(
    file: UploadFile = File(...),
    language_code: str | None = Form(None),
    user: User = Depends(get_current_user),
):
    """Transcribe an audio recording to text, so the app can show it for review.
    Optional language_code (e.g. "ta") improves accuracy; otherwise auto-detected."""
    transcript = await voice_service.speech_to_text(file, language_code=language_code)
    return {"transcript": transcript}


# ---------- Text in -> spoken reply out (send a reviewed transcript) ----------
@router.post("/chat-voice")
async def chat_voice(
    body: ChatRequest,
    background_tasks: BackgroundTasks,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Voice-mode send: the app has already transcribed the user's speech and the user
    confirmed it. This takes the text, runs the agent, and returns the reply text
    plus spoken audio (base64).
    """
    persona = _get_owned_persona(body.persona_id, user, db)
    reply = run_agent(
        db=db, persona_id=persona.id, user_message=body.user_message,
        background_tasks=background_tasks, brief=True,
    )
    audio = await voice_service.text_to_speech(
        text=reply, voice_id=persona.elevenlabs_voice_id or DEFAULT_VOICE_ID,
        model_id=FLASH_TTS_MODEL, language_code=_lang_code(persona.language),
    )
    return {"reply": reply, "audio_base64": base64.b64encode(audio).decode("ascii")}


# ---------- Full voice loop (audio in -> audio out) ----------
@router.post("/voice-chat")
async def voice_chat(
    background_tasks: BackgroundTasks,
    persona_id: str = Form(...),
    file: UploadFile = File(...),
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    The "phone call" loop:
      user's audio  ->  STT (Scribe)  ->  agent  ->  TTS (persona voice)  ->  audio reply
    The transcript is returned in a header so the app can show the captions.
    """
    persona = _get_owned_persona(persona_id, user, db)

    transcript = await voice_service.speech_to_text(file)
    reply = run_agent(
        db=db, persona_id=persona.id, user_message=transcript,
        background_tasks=background_tasks, brief=True,
    )
    audio = await voice_service.text_to_speech(
        text=reply, voice_id=persona.elevenlabs_voice_id or DEFAULT_VOICE_ID,
        model_id=FLASH_TTS_MODEL, language_code=_lang_code(persona.language),
    )
    # Return JSON with the FULL transcript + reply and the audio as base64.
    # (Earlier this used HTTP headers, but those are Latin-1 only and size-limited,
    #  which truncated long replies and broke on em-dashes / non-English text.)
    return {
        "transcript": transcript,
        "reply": reply,
        "audio_base64": base64.b64encode(audio).decode("ascii"),
    }


# ---------- Free synthetic voice samples (for demoing cloning, no real-person data) ----------
_SYNTHETIC_SAMPLE_TEXT = (
    "Hello there. This is a synthetic voice sample created for a demonstration. "
    "I was generated entirely by artificial intelligence, so I am not a real person. "
    "You can use my voice to test how voice cloning works, from start to finish. "
    "The quick brown fox jumps over the lazy dog. Thank you for listening."
)
_synthetic_cache: dict[str, bytes] = {}  # gender -> mp3 bytes (per process)


@router.get("/synthetic-voice")
async def synthetic_voice(gender: str = "male", user: User = Depends(get_current_user)):
    """
    Returns a free, AI-generated voice sample (male or female) as an MP3.
    Because it is synthetic (not a real person), it can be uploaded and cloned to
    demonstrate the cloning feature without any consent, copyright or ethics concerns.
    """
    g = "female" if gender.strip().lower().startswith("f") else "male"
    if g not in _synthetic_cache:
        # Pick an English voice of that gender from the Voice Library (sample text is English).
        matches = await voice_service.list_voices(gender=g, language="en", limit=1)
        voice_id = matches[0]["voice_id"] if matches else DEFAULT_VOICE_ID
        _synthetic_cache[g] = await voice_service.text_to_speech(_SYNTHETIC_SAMPLE_TEXT, voice_id)

    return Response(
        content=_synthetic_cache[g],
        media_type="audio/mpeg",
        headers={"Content-Disposition": f'attachment; filename="synthetic-{g}-voice.mp3"'},
    )


# ---------- Voice management ----------
@router.post("/clone-voice")
async def clone_voice(
    name: str = Form(...),
    description: str = Form(...),
    file: UploadFile = File(...),
    persona_id: str | None = Form(None),
    rights_confirmed: bool = Form(False),
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Clone a voice from an audio sample. If a persona_id is given, the new
    ElevenLabs voice_id is saved onto that persona, so all future voice replies
    use this cloned voice (e.g. Grandpa Arthur's real voice).

    Consent gate: the caller MUST confirm (rights_confirmed=true) that the recording
    is the intended person's voice and that they have the right to use it. This is
    enforced server-side so it cannot be bypassed by calling the API directly.
    """
    if not rights_confirmed:
        raise HTTPException(
            status_code=400,
            detail="You must confirm you have the right to use this recording before cloning a voice.",
        )

    voice_id = await voice_service.clone_voice(name, description, [file])

    saved_to = None
    if persona_id:
        persona = _get_owned_persona(persona_id, user, db)  # verifies it's the user's persona
        persona.elevenlabs_voice_id = voice_id
        db.commit()
        saved_to = persona.id

    return {
        "message": f"Cloned voice '{name}'.",
        "voice_id": voice_id,
        "saved_to_persona": saved_to,
    }


_PREVIEW_TEXT = "Hi, this is a preview of how I sound. It's lovely to be able to talk with you."


def _preview_line(language: str | None) -> str:
    """
    A short sample sentence to speak in the preview. So the preview is actually heard in
    the persona's language (e.g. Tamil, not English), we generate the line in that
    language; English (the default) uses a fixed line to stay fast. Falls back to the
    English line if anything goes wrong.
    """
    lang = (language or "English").strip()
    if not lang or lang.lower() == "english":
        return _PREVIEW_TEXT
    try:
        from app.services.llm_service import get_llm
        from langchain_core.messages import HumanMessage
        llm = get_llm(model_id=settings.BEDROCK_VOICE_MODEL_ID, max_tokens=80)
        resp = llm.invoke([HumanMessage(content=(
            f"Write ONE short, warm sentence (about 8-15 words) introducing yourself as a voice "
            f"preview, written entirely and naturally in {lang}. No quotes, no emojis, no stage "
            f"directions, no translation or explanation - output only the sentence itself."
        ))])
        text = (resp.content if isinstance(resp.content, str) else str(resp.content)).strip()
        return text or _PREVIEW_TEXT
    except Exception:
        return _PREVIEW_TEXT


@router.get("/preview-voice")
async def preview_voice(
    voice_id: str,
    language: str | None = None,
    user: User = Depends(get_current_user),
):
    """
    Speak a short sample in the given voice so the user can hear it (e.g. right after
    cloning). The sample is spoken in the persona's `language` (e.g. Tamil), not just
    English. Works for any voice_id — a cloned voice or a ready-made one. Returns the
    audio as base64 JSON so the app can play it (no Latin-1 header issues).
    """
    sample = _preview_line(language)
    audio = await voice_service.text_to_speech(
        sample, voice_id, model_id=FLASH_TTS_MODEL, language_code=_lang_code(language)
    )
    return {"audio_base64": base64.b64encode(audio).decode("ascii")}


@router.get("/voices")
async def list_voices(
    gender: str | None = None,
    age: str | None = None,
    language: str | None = None,
    use_case: str | None = "conversational",
    limit: int = 5,
    user: User = Depends(get_current_user),
):
    """
    Search the ElevenLabs **Voice Library** (many languages), filtered by preference.

    - gender:   "male" or "female"
    - age:      "young", "middle_aged" or "old"
    - language: ISO code such as "en", "ta", "hi", "es", "ar", "ja"
    - use_case: defaults to "conversational" (best fit for a talking persona)
    - limit:    how many to return (default 5)

    All filters are optional and applied by ElevenLabs server-side. Each voice
    includes a preview_url so the app can let the user hear it before choosing.
    """
    voices = await voice_service.list_voices(
        gender=gender, age=age, language=language, use_case=use_case, limit=limit
    )
    return {
        "count": len(voices),
        "filters": {"gender": gender, "age": age, "language": language, "use_case": use_case},
        "available_voices": voices,
    }
